### PR TITLE
fix(key-manager): key manager setup & ui

### LINKED ISSUE #39: Log out button on api manager does not redirect on create or edit page
## Expected Behavior

Logging out from `/create` or `/edit/[key]` should redirect to `/login`

## Current Behavior

Calling signOut by pressing the Log Out button deauthenicates the user, but does not redirect
This is not an issue on the dev environment, but seems to show up in prod

### PR DESCRIPTION
**Pull request by andrew-wang0**
## Related Issue

Closes #39

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code involves a change to the database schema.
- [ ] My code requires a change to the documentation.

### CODE REVIEW

File: apps/key-manager/src/components/auth/SignOut.tsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
+"use client";
+
+import { DropdownMenuItem } from "@/components/ui/dropdown-menu";
+import { LogOutIcon } from "lucide-react";
+import { signOut } from "next-auth/react";
+
+export default function SingOut() {
```
Comment (laggycomputer) [inline apps/key-manager/src/components/auth/SignOut.tsx:7]: Component still misnamed.

**Review by laggycomputer — CHANGES_REQUESTED** [review]

File: apps/key-manager/src/components/auth/SignOut.tsx (hunk 1 above)
Comment (laggycomputer) [reply apps/key-manager/src/components/auth/SignOut.tsx:7]: `export default` allowed the correct name to be used on import despite this typo. This line is the last typo of this type as far as I know.

File: apps/key-manager/src/components/auth/SignOut.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  function handleSignOut() {
+    signOut({
+      redirect: true,
+      redirectTo: "/",
```
Comment (laggycomputer) [inline apps/key-manager/src/components/auth/SignOut.tsx:11]: It may be best to redirect straight to `/login` (which is also easier for me to test locally).

File: apps/key-manager/src/components/layout/Header.tsx [hunk 3]
```diff
@@ -23,29 +22,14 @@ const Header = async () => {
...
-                  className={"rounded-full"}
-                  width={40}
-                  height={40}
-                  src={session.user.image}
-                  alt={session.user.email}
-                />
-              )}
+            <DropdownMenuTrigger asChild>
+              <Avatar>
+                <AvatarImage src={session.user.image ?? ""} alt={"avatar"} />
```
Comment (laggycomputer) [inline apps/key-manager/src/components/layout/Header.tsx:27]: An explicit `<AvatarFallback>` is needed after `<AvatarImage>` with the desired content.

**Review by laggycomputer — CHANGES_REQUESTED** [review]

File: apps/key-manager/src/components/layout/Header.tsx (hunk 3 above)
Comment (laggycomputer) [reply apps/key-manager/src/components/layout/Header.tsx:27]: Docs: https://www.radix-ui.com/primitives/docs/components/avatar#fallback

Also consider `delayMs` to prevent fallback from appearing at first.

**Comment by laggycomputer** [comment]
PR title has a duplicate colon.

**Review by laggycomputer — APPROVED** [review]
