### PR TITLE
fix (study-rooms): fix pruning old time slots

### LINKED ISSUE #375: Study room missing todays rooms
zotmeet found another study room bug
## Expected Behavior
When querying same day rooms, rooms should appear

## Current Behavior
When querying same day rooms, some rooms before a certain time are missing

Image

## Possible Solution
check timezones :C

### PR DESCRIPTION
**Pull request by ZackeryHe**
## Description

was using wrong time

btw probably not worth moving anything else in the time.ts util file bc they are too format specific

## Related Issue
https://github.com/icssc/anteater-api/issues/375

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code involves a change to the database schema.
- [ ] My code requires a change to the documentation.

### CODE REVIEW

File: apps/data-pipeline/study-location-scraper/src/time.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+export function getLaWallClockAsUtcDate(): Date {
+  const parts = new Intl.DateTimeFormat("en-CA", {
```
Comment (laggycomputer) [inline apps/data-pipeline/study-location-scraper/src/time.ts]: This is Canadian English ("Californian English" does not exist, no matter how different we think valley people sound)! Was that intended?

File: apps/data-pipeline/study-location-scraper/src/time.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
+export function getLaWallClockAsUtcDate(): Date {
```
Comment (laggycomputer) [inline apps/data-pipeline/study-location-scraper/src/time.ts]: This name is a little strange. Why not something like `losAngelesNowNaive`?

**Review by laggycomputer — CHANGES_REQUESTED** [review]
I still think the best thing to do is just to add a timezone to the database columns, instead of futzing with JS time APIs.

Also see naming on the other PR.

**Comment by ZackeryHe** [comment]
we could do changing to timestamptz in another issue. and itll probably make adding ALP support easier

**Review by laggycomputer — APPROVED** [review]
