### PR TITLE
fix: Consolidating Common Data Models

### LINKED ISSUE #142: Extract common course data models
Data like GE categories should be unified in `apps/api/schema/lib` where possible. Other candidates should be investigated.

_Originally posted by @ecxyzzy in https://github.com/icssc/anteater-api/pull/129#discussion_r2025949362_

### PR DESCRIPTION
**Pull request by matt-franklin225**
## Description

Implemented the following changes to remove redundant code across the API codebase:

1. Created helper functions for each HTTP status code response (200, 404, 422, 500) to clean up a large amount of repeated code in `apps/api/src/rest/routes`, adding these helpers into `apps/api/src/schema/base/response.ts`.
2. Designed base schemas for take, skip, and cursor, which are used several times across `apps/api/src/schema/base`. The base schemas are declared in `apps/api/src/schema/base/search-modifiers.ts`.
3. Added several more base schemas across several files in the same directory to remove many redundant lines from the declaration of near-identical schemas.
4. Removed redundant declarations of GE Categories in the schema.

## Related Issue

Will close #142 

## Motivation and Context

This cleans up redundant code in the codebase, improving readability and adding helper functions and exported variables to improve future work.

## How Has This Been Tested?

The changes have been tested on a local instance.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code involves a change to the database schema.
- [ ] My code requires a change to the documentation.

### CODE REVIEW

File: apps/api/src/rest/routes/base/responses.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+  ({
+    content: { "application/json": { schema: errorSchema } },
+    description: "Parameters failed validation",
+  }) as const;
+
+export const response500 = () =>
+  ({
+    content: { "application/json": { schema: errorSchema } },
+    description: "Server error occurred",
+  }) as const;
```
Comment (laggycomputer) [inline apps/api/src/rest/routes/base/responses.ts]: Make these named functions. There's no reason to incur the cost of arrows here.

**Review by laggycomputer — CHANGES_REQUESTED** [review]

**Review by laggycomputer — CHANGES_REQUESTED** [review]
You should apply your changes to the new dining API, then we should merge this before it gets too big.

**Review by laggycomputer — CHANGES_REQUESTED** [review]
Minor thing: `isCursor` should be an optional field in an object. Formal parameters with default values get messy if you ever want to have more than one.
